# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('steps', models.CharField(blank=True, max_length=1000, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(blank=True, null=True, to='cook.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipies',
            field=models.ManyToManyField(blank=True, null=True, to='cook.Recipe'),
        ),
    ]
